// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA95O33pSpBJdLsUviyJqZdf1MkV70LebI',
    appId: '1:667982982906:web:b4a6115387737e3e5d2343',
    messagingSenderId: '667982982906',
    projectId: 'quraanlife-50941',
    authDomain: 'quraanlife-50941.firebaseapp.com',
    storageBucket: 'quraanlife-50941.appspot.com',
    measurementId: 'G-VNXW0T91HB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjyAte5J7rlFDa5wI-F1_op6uBW0rwKRs',
    appId: '1:667982982906:android:b3b143b87f8197ef5d2343',
    messagingSenderId: '667982982906',
    projectId: 'quraanlife-50941',
    storageBucket: 'quraanlife-50941.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcotzGMyNfGMOzuBKyocYQeJaC8iWCH7Y',
    appId: '1:667982982906:ios:7f04f1e0cfb208be5d2343',
    messagingSenderId: '667982982906',
    projectId: 'quraanlife-50941',
    storageBucket: 'quraanlife-50941.appspot.com',
    iosBundleId: 'com.example.quranlife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcotzGMyNfGMOzuBKyocYQeJaC8iWCH7Y',
    appId: '1:667982982906:ios:7f04f1e0cfb208be5d2343',
    messagingSenderId: '667982982906',
    projectId: 'quraanlife-50941',
    storageBucket: 'quraanlife-50941.appspot.com',
    iosBundleId: 'com.example.quranlife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA95O33pSpBJdLsUviyJqZdf1MkV70LebI',
    appId: '1:667982982906:web:5927f27c049734b85d2343',
    messagingSenderId: '667982982906',
    projectId: 'quraanlife-50941',
    authDomain: 'quraanlife-50941.firebaseapp.com',
    storageBucket: 'quraanlife-50941.appspot.com',
    measurementId: 'G-94LP5MN6KM',
  );
}
